//
// Created by nvk on 12/07/2019.
//

#ifndef UPSEM_CONSTANTS_H
#define UPSEM_CONSTANTS_H

#define MAX_BUFFER_SIZE_BYTES 4096
#define MAX_TIMEOUT_BEFORE_DISCONNECT_MS 15e3
#define MAX_TIMEOUT_BEFORE_REMOVED_MS 900e3
#define LOBBY_PREP_TIME_MS 30e3
#define LOBBY_THREAD_SLEEP_MS 5

#define BLACKJACK 21

#endif //UPSEM_CONSTANTS_H
