//
// Created by nvk on 12/07/2019.
//

#ifndef UPSEM_CONSTANTS_H
#define UPSEM_CONSTANTS_H

#define MAX_BUFFER_SIZE_BYTES 4096
#define MAX_TIMEOUT_BEFORE_DISCONNECT_MS 15000.0
#define MAX_TIMEOUT_BEFORE_REMOVED_MS 900000.0
#define LOBBY_UPDATE_REQUEST_MS 5000.0
#define LOBBY_THREAD_SLEEP_MS 5

#endif //UPSEM_CONSTANTS_H
