//
// Created by itznu on 12/25/2019.
//

#ifndef UPSEM_LOBBYSTATE_H
#define UPSEM_LOBBYSTATE_H

enum LobbyState {
    LOBBY_STATE_WAITING,
    LOBBY_STATE_PREPARING,
    LOBBY_STATE_IN_GAME,
    LOBBY_STATE_FINISHED
};

#endif //UPSEM_LOBBYSTATE_H
